services:
  asir_web1:
    image: httpd:2.4
    ports:
      - "8000:80"
    volumes:
      - ./paginas:/usr/local/apache2/htdocs

    container_name: asir_web1
    networks:
      red_web:
        ipv4_address: 172.28.0.0
      red_interna:
        ipv4_address: 172.28.0.30
    hostname: asir_web1
  asir_web2: 
    image: httpd:2.4
    ports:
      - "9080:80"
    volumes:
      - ./paginas:/usr/local/apache2/htdocs
    container_name: asir_web2
  networks:
      red_web:
        ipv4_address: 172.28.0.0
      red_interna:
        ipv4_address: 172.28.0.40
  hostname: asir_web2