services:
  asir_web1:
    image: httpd:2.4
    ports:
      - "8000:80"
    volumes:
      - ./paginas:/usr/local/apache2/htdocs

    container_name: asir_web1
    networks:
      my-network:
        ipv4_address: 172.29.0.30
  asir_web2: 
    image: httpd:2.4
    ports:
      - "9080:80"
    volumes:
      - ./paginas:/usr/local/apache2/htdocs
    container_name: asir_web2
    networks:
      my-network:
        ipv4_address: 172.29.0.40
networks:
  my-network:
    ipam:
      config:
        - subnet: 172.29.0.0/16
          gateway: 172.29.0.1