services:
  asir_apache-2:
    container_name: asir_apache-2
    image: httpd:latest
    ports:
      - "80:80"
    networks:
      mi-red:
        ipv4_address: 10.1.0.50
        # ip fija del contenedor
    volumes:
      - ./paginas:/usr/local/apache2/htdocs
      - ./conf:/usr/local/apache2/conf
  asir_bind9-2:
    container_name: asir_bind9-2
    image: ubuntu/bind9
    # usamos esta imagen para ver los logs
    # la imagen internetconsortium no muestra logs
    platform: linux/amd64
    ports:
      - 53:53
      #Mapeo de puertos
    networks:
    #Creamos la red y le damos ip al DNS
      mi-red:
        ipv4_address: 10.1.0.2
    volumes:
    #Volumenes
      - ./config:/etc/bind
      - ./zonas:/var/lib/bind
  cliente-2:
    container_name: asir_cliente-2
    image: ubuntu
    platform: linux/amd64
    tty: true
    stdin_open: true
    networks:
      mi-red:
        ipv4_address: 10.1.0.15
networks:
  mi-red:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16 
          gateway: 10.1.0.1